# Generated by Django 5.2 on 2025-04-25 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_show_available_seats_alter_show_team1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ticket_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'show')},
        ),
    ]
